# costom boilerplate file from sisakulint
name: Deploy sisakulint document

on:
  # Trigger the workflow every time you push to the main branch
  # Using a different branch name? Replace main with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  pull_request:
    branches: [main]

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@3046833d9aacfd7745c5264b7f3af851c3e2a619 # v2.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: "latest"
          extended: true
      - name: Build Hugo
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python ogp_proxy.py &
          hugo --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: "./public"
      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
